### ISSUE TITLE
[react/jsx-handler-names] Definition for rule 'react/jsx-handler-names' was not found

### ISSUE THREAD

**Issue by bitspook** [gajus/canonical#11]
Canonical is showing this error. Just reporting in case a plugin or something is missing.

**Comment by gajus** [comment]
Depends on https://github.com/yannickcr/eslint-plugin-react/issues/334.

**Comment by gajus** [comment]
https://github.com/gajus/canonical/commit/6adaba390fdf591ebd42bd0b8713543fbe72fe18
