### ISSUE TITLE
Faulty build for 2.7.6

### ISSUE THREAD

**Issue by bitspook** [gajus/canonical#13]
``` js
{
    "root": true,
    "extends": [
        "/Users/gajus/Documents/dev/canonical-code-style/eslint-config-canonical/index.js"
    ]
}
```

https://github.com/gajus/canonical/blob/bc8955b0009c0ef07fe3bacf93630f5d13a1ad61/src/linters/js/eslintrc.json#L4

Hardcoded path is making canonical fail with error in v2.7.6

**Comment by gajus** [comment]
Fixed in @ca5d1d7a6491c5908aa4ab1ee62627f93f761a8c.
