### ISSUE TITLE
Definition for rule not found

### ISSUE THREAD

**Issue by bitspook** [gajus/canonical#23]
Getting some errors regarding missing rule definitions:

```
[no-unsafe-finally] Definition for rule 'no-unsafe-finally' was not found

[no-useless-computed-key] Definition for rule 'no-useless-computed-key' was not found
```

**Comment by gajus** [comment]
Thats odd. These rules have been added to ESLint v2.9.0.

https://github.com/eslint/eslint/blob/06f6252a1e9a4daf7528023ed904d9d01919ec7d/CHANGELOG.md

@channikhabra Can you confirm that you are using the most recent Canonical version and that it is bundled with ESLint v2.9.0?

**Comment by bitspook** [comment]
My bad. Should've upgraded canonical before creating the issue.
