### ISSUE TITLE
SCSS linting property-sort-order error is unclear

### ISSUE THREAD

**Issue by bitspook** [gajus/canonical#3]
<img width="1068" alt="screen shot 2015-11-19 at 8 53 29 pm" src="https://cloud.githubusercontent.com/assets/1437091/11274629/afc24500-8eff-11e5-8b7f-e886c8cab468.png">

**Comment by gajus** [comment]
Doesn't this simply say that they are in wrong order?

**Comment by gajus** [comment]
It says that it is expecting:

``` css
border-radius;
border-bottom-right-radius;
```

but you have:

``` css
border-bottom-right-radius;
border-radius;
```

**Comment by bitspook** [comment]
You're right. I thought it was circular. I am stupid 😅

**Comment by gajus** [comment]
I admit it is confusing. The first time I saw a similar error I was puzzled too.
