### ISSUE TITLE
No scss-lint rule for separating similar blocks of styles

### ISSUE THREAD

**Issue by bitspook** [gajus/canonical#4]
It does not seem to have rule for separating blocks of styles with empty lines. That was a nice one, made scss files look much cleaner and sensible.

**Comment by gajus** [comment]
I know that when I was integrating https://github.com/sasstools/sass-lint, it did not have this feature. I am investigating if it was added since; I remember there was a ticket for it.

**Comment by gajus** [comment]
It appears this feature does not exist at the moment. I have raised a feature request https://github.com/sasstools/sass-lint/issues/414
