### ISSUE TITLE
Cyclic jsdoc warnings

### ISSUE THREAD

**Issue by bitspook** [gajus/canonical#7]
``` js
    /**
     * Updates app state by fetching new data from API server for latitude and longitude of new location.
     *
     * @param {number} lat Latitude
     * @param {number} lng Longitude
     *
     * @returns {undefined}
     */
```

Above code gives warning: `Newline required after description`, and `Redundant return statement`.

``` js
    /**
     * Updates app state by fetching new data from API server for latitude and longitude of new location.

     * @param {number} lat Latitude
     * @param {number} lng Longitude
     *
     * @returns {undefined}
     */
```

Jsdoc can't read after description here apparently because of missing `*`. What do `Newline required` mean here?

Also,

``` js
    /**
     * Updates app state by fetching new data from API server for latitude and longitude of new location.
     *
     * @param {number} lat Latitude
     * @param {number} lng Longitude
     *
     */
```

This code gives warning: `Missing JSDoc @returns for function`

The subjected function do not have a return statement. Adding a return {undefined} says redundant return, and removing it says return required.

**Comment by gajus** [comment]
My guess is that you have a local eslint thats extending canonical rules.

**Comment by bitspook** [comment]
No I made sure to remove that this time. I dont' even have a global eslintrc

**Comment by gajus** [comment]
``` sh
curiosity:~ gajus$ echo '/**
 * Updates app state by fetching new data from API server for latitude and longitude of new location.
 *
 * @param {number} lat Latitude
 * @param {number} lng Longitude
 * @returns {undefined}
 */
export default () => {
    return 'test';
};' | canonical --stdin --linter js --output-format json
{
    "messages": [],
    "errorCount": 0,
    "warningCount": 0
}
```

These command line additions are already saving me time. : )

**Comment by bitspook** [comment]
The error was that the function I was documenting was a class function (`foo() { }`), and it could not recognise that syntax. Changing it to `foo = () => {}` solves the problem. 

I am closing this issue since turns out that it don't really belong to canonical. Not sure where it belongs.
