### ISSUE TITLE
Display some feedback when no-errors are found in linting

### ISSUE THREAD

**Issue by bitspook** [gajus/canonical#8]
I have to double check every time just to make sure if linting is all correct or if it's breaking for some reason and not showing error (which it used to do for a past issue #7 ).

**Comment by gajus** [comment]
What output do you suggest?

**Comment by bitspook** [comment]
Anything that could indicate a success would be great. Perhaps an empty table with no errors, or a message saying "No linting errors. Go by yourself some ice-cream 🍨"

**Comment by gajus** [comment]
<img width="811" alt="screen shot 2015-11-28 at 15 50 44" src="https://cloud.githubusercontent.com/assets/973543/11452656/d2d9c8ee-95e7-11e5-966a-76fc380ccd86.png">

<img width="812" alt="screen shot 2015-11-28 at 15 51 20" src="https://cloud.githubusercontent.com/assets/973543/11452659/fe284fd4-95e7-11e5-8d91-78f9afe1a503.png">

https://github.com/gajus/canonical/commit/7143538b9352ab1a6c5fb2a2546d0279e3c4dc99
